[package]
name = "kyute-shell"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# windowing
anyhow = "1.0.43"
winit = "0.26.0"
euclid = "0.22"   # basic 2D geometric types
svgtypes = "0.5.0"  # SVG path parser and path segment definitions
palette = "0.5.0"   # colors
bitflags = "1.2.1"
lazy_static = "1.4.0"
once_cell = "1.7.2"
raw-window-handle = "0.3.3"
tracing = "0.1.25"
thiserror = "1.0.24"
graal = { path = "../graal" }
windows = "0.9.1"
skia-safe = { version = "0.43.0", features = ["vulkan", "textlayout"] }

[build-dependencies]
windows = "0.9.1"