[package]
name = "miniqt-sys"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "*"

[build-dependencies]
bindgen = "0.47.0"
cmake = "0.1.40"
cc = "1.0.28"