[package]
name = "kyute2-macros"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.37", features = ["full"] }
proc-macro2 = "1.0.67"

[lib]
proc-macro = true